# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXdp7d_jPmsu9kwrZ0kwFlD9lxIuTrFw
"""

a, b = map(int, input().split())
def count_Primes_nums(n):
    ctr = 0

    for num in range(n):
        if num <= 1:
            continue
        for i in range(2, num):
            if (num % i) == 0:
                break
        else:
            ctr += 1

    return ctr
if a <= b:
  c = count_Primes_nums(b+1) - count_Primes_nums(a)
  print('main order - amount:', ' ', c)
else:
  d = count_Primes_nums(a+1) - count_Primes_nums(b)
  print('reverse order - amount:', ' ', d)