# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hBdXet1c8griZidTar7tZcaP7mw87Bfr
"""

funcs = ('sum', 'average', 'lcd', 'gcd', 'min', 'max')
func = input()
numbers = []
if func in funcs:
  while True:
    temp = input()
    if temp == 'end':
      break
    numbers.append(int(temp))
else:
  print("Invalid command")

import math

if func == 'sum':
  print(sum(numbers))
elif func == 'average':
  print(round(sum(numbers)/len(numbers), 2))
elif func == 'lcd':
  lcm = 1
  for i in numbers:
    lcm = lcm*i//math.gcd(lcm, i)
  print(lcm)
elif func == 'gcd':
  import numpy as np

  arr = np.array(numbers)
  result = np.gcd.reduce(arr)
  print(result)
elif func == 'min':
  print(min(numbers))
elif func == 'max':
  print(max(numbers))