# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXdp7d_jPmsu9kwrZ0kwFlD9lxIuTrFw
"""

a = int(input())
b = int(input())
k = int(input())
def add_using_bitwise(center_a, center_b):
    while center_b != 0:
        carry = center_a & center_b
        center_a = center_a ^ center_b
        center_b = carry << 1
    return center_a
print(add_using_bitwise(a, b))
if add_using_bitwise(a, b) == k:
  print('YES')
else:
  print('NO')