# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMQbfa7gauuaCoDs7d2c-gs8Z_TDPgXs
"""

def make_original_text(secret_mesaage):
    parts = secret_mesaage.split()
    mapping = {int(part[1:]): part[0] for part in parts}
    sorted_keys = sorted(mapping.keys())
    original_text = ''.join(mapping[key] for key in sorted_keys)
    return original_text
secret = input()
print(make_original_text(secret))