# -*- coding: utf-8 -*-
"""hello-python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16KXjQRSPwx2SzfJnJ_Y7SUlJxwbpXSOZ
"""

print('Hello Python')