# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vBP1mkkDYx2EWrc9gPpndcgyOSEEKqJv
"""

import re

def remove_punctuation(input_text):
    cleaned_text = re.sub(r'[^\w\s]', '', input_text)
    return cleaned_text

def count_non_matching_letters(word1, word2):
    max_length = max(len(word1), len(word2))
    word1 = word1.ljust(max_length, '_')
    word2 = word2.ljust(max_length, '_')

    non_matching_letters = sum(1 for a, b in zip(word1, word2) if a != b)
    return non_matching_letters

def find_similar_words(n, sentence, word):
    edit_sentence = remove_punctuation(sentence)
    words = edit_sentence.split()
    result = []

    for w in words:
        if count_non_matching_letters(word, w) <= n:
            result.append(w)

    return result

n = int(input())
sentence = input()
word = input()

for wo in find_similar_words(n, sentence, word):
    print(wo)