# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXdp7d_jPmsu9kwrZ0kwFlD9lxIuTrFw
"""

a = int(input())
b = int(input())
n = str(bin(a^b))
one_count = 0
for i in n:
    if i == "1":
      one_count += 1
print(one_count)