# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fBI0CEFjBd91tJ9CVQtSEGgNayT6l2fL
"""

def remove_hashtags_after_at(input_text):
    modified_text = input_text
    at_index = modified_text.find('@')
    while at_index != -1:
        hashtag_index = modified_text.find('#', at_index)
        if hashtag_index != -1:
            modified_text = modified_text[:hashtag_index] + modified_text[hashtag_index+1:]
        at_index = modified_text.find('@', at_index + 1)
    return modified_text
def format_text(input_text):
    modified_text = remove_hashtags_after_at(input_text)
    modified_text = ' '.join(modified_text.split())
    modified_text = modified_text.replace('\\n', '\n')
    return modified_text
input_text = input()
formatted_text = format_text(input_text)
print(f'Formatted Text: {formatted_text}')