# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fBI0CEFjBd91tJ9CVQtSEGgNayT6l2fL
"""

def find_receiver_plates(postal_codes, target_sum):
    postal_indices = {}
    found_pairs = []
    for i, code in enumerate(postal_codes):
        complement = target_sum - code
        if complement in postal_indices:
            found_pairs.append((postal_indices[complement], i))
        postal_indices[code] = i
    return found_pairs
postal_codes = list(map(int, input().split()))
target_sum = int(input())
result = find_receiver_plates(postal_codes, target_sum)
if result:
    result = sorted(sum(pair) for pair in result)
    print('\n'.join(map(str, result)))
else:
    print("Not Found!")