# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vwyXFZU_f8evh5xdLT1qjxIXbbZjQjVr
"""

#import matplotlib.pyplot as plt

try:
    players = input().split()
    player1, player2 = players[0], players[1]

    health_values = input().split()
    health1, health2 = int(health_values[0]), int(health_values[1])

    damage_values = input().split()
    damage_A, damage_B, damage_C = int(damage_values[0]), int(damage_values[1]), int(damage_values[2])

    score1, score2 = 0, 0
    rounds = [1, 2, 3]
    player1_scores, player2_scores = [], []

    for _ in rounds:
        cards = input().split()
        card1, card2 = cards[0], cards[1]

        damage_player1 = locals()["damage_" + card1]
        damage_player2 = locals()["damage_" + card2]

        if damage_player1 > damage_player2:
            score1 += 1

        elif damage_player1 < damage_player2:
            score2 += 1

        health2 -= damage_player1
        health1 -= damage_player2

        player1_scores.append(score1)
        player2_scores.append(score2)

    print(f"{player1} -> Score: {score1}, Health: {health1}")
    print(f"{player2} -> Score: {score2}, Health: {health2}")

    #with open('result.txt', 'w') as file:
        #file.write(f"{player1} -> Score: {score1}, Health: {health1}\n")
        #file.write(f"{player2} -> Score: {score2}, Health: {health2}\n")

    #plt.plot([1, 2, 3], player1_scores, label=player1)
    #plt.plot([1, 2, 3], player2_scores, label=player2)
    #plt.xlabel('Players')
    #plt.ylabel('Scores')
    #plt.legend()
    #plt.title('Players Scores Over Rounds')
    #plt.show()

except ValueError:
    print("Invalid Command.")

except IndexError:
    print("Invalid Command.")