# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fBI0CEFjBd91tJ9CVQtSEGgNayT6l2fL
"""

def E(emails):
    D = set()
    for email in emails:
        if '@' in email:
          d = email.split('@')[1]
          D.add(d)
    sorted_d = sorted(D)
    for d in sorted_d:
        print(d)
n = int(input().strip())
email_list = [input().strip() for _ in range(n)]
E(email_list)