# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXdp7d_jPmsu9kwrZ0kwFlD9lxIuTrFw
"""

a = int(input())
b = int(input())
n = int(input())
for i in range(n):
  d = int(input())
  c = (b<<32) + a
  if c&(1<<(d)) == 0:
    print('no')
  else:
    print('yes')